### ISSUE TITLE
 Argo-events keeps on trigger workflow through webhook and workflow running on loop

### ISSUE THREAD

**Issue by nishit93-hub** [vfarcic/argo-events-demo#2]
Hi,

I am using Argo-events to trigger workflow through  webhook when ever there is push on git repo and Argo-image-updater to update container image.

Now whenever i push changes on git repo, argo-events trigger the workflow through webhook and build the docker image. After that Argo-image-updater  consider the new image and write it back to git repo, where it trigger new workflow. By this workflow keeps on running on loop.

Is there way i can tell argo-events not to trigger workflow whenever Argo-image-updater write back to git repo?

**Comment by vfarcic** [comment]
You'd need to filter Argo Workflows so that builds are not executed when specific files are pushed. That is annoying and the main reason why I'm not using Argo CD Image Updater extensively. The current model assumes that app manifests are not in the same repo as app code (which is not a good assumption).

**Comment by nishit93-hub** [comment]
No, the app manifest and app code are in same repo.

**Comment by nishit93-hub** [comment]
I am  using argo webhooks is post-receive hooks and now there i have added the code for git that will not execute the post-receive hook on specific file pushed.
